# Generated by Django 3.2.4 on 2021-07-01 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='quantity',
            new_name='quantity_Required',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 21, 5, 22, 113511)),
        ),
    ]
