# Generated by Django 3.2.4 on 2021-07-02 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210702_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 5, 44, 49, 454505)),
        ),
    ]
