# Generated by Django 3.2.4 on 2021-07-02 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210703_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='user_check',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 1, 53, 35, 616522)),
        ),
    ]
