# Generated by Django 3.2.4 on 2021-07-03 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tbsp', 'Tablespoon'), ('lbs', 'Pound'), ('oz', 'Ounce'), ('unit', 'Unit'), ('gram', 'Gram'), ('liter', 'Liter')], default='unit', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 6, 41, 18, 792087)),
        ),
    ]
